[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_extra_dirs = ../shared
lib_deps = 
    adafruit/Adafruit PN532
    adafruit/Adafruit BusIO
    bblanchon/ArduinoJson

; Local serial upload (from dev PC)
upload_port = /dev/ttyUSB0

[env:esp32c3_ota]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_extra_dirs = ../shared
lib_deps = 
    adafruit/Adafruit PN532
    adafruit/Adafruit BusIO
    bblanchon/ArduinoJson

; Remote WiFi OTA upload
upload_protocol = espota
upload_port = fonie-esp32.local
