[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.filesystem_size = 1m
board_build.core = earlephilhower
lib_extra_dirs = ../shared
lib_deps = adafruit/Adafruit NeoPixel

; Local USB upload (from dev PC)
upload_protocol = picotool

[env:pico_swd]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
lib_extra_dirs = ../shared
lib_deps = adafruit/Adafruit NeoPixel

; Remote SWD upload via Pi + OpenOCD
upload_protocol = custom
upload_command =
    openocd
    -f ${PROJECT_DIR}/openocd-pi-swd.cfg
    -c "program ${BUILD_DIR}/firmware.elf verify reset exit"
